sudo: required
services:
  - docker
language: go
go:
  - 1.16
before_script:
  - sudo apt-get install -qq sshpass
script:
  - make test
  - make build
after_success:
  - sh .travis/deploy_directory.sh